
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword"
	content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>Admin| Backend</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('images/front/favicon.ico') ?>" />
    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    include_once("admincss.phtml");
    ?>

</head>
<body style="background: url(<?php echo $dynamicPath; ?>/images/backend/home_transfer_main_banner.jpg) no-repeat; height: 100%; background-size: cover;">
<div>
 <a href="<?php echo $dynamicPath; ?>"><img src="<?php echo $dynamicPath; ?>/images/backend/logo.png" style="height: 100px;" ></a>
	<section id="container">
		<?php
	       echo $this->content;
           include_once('adminjs.phtml');
	 ?>
	</section>
</div>
</body>
