<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
	case 'adminlogin':
		switch ($action) {
            case 'login':
				 $this->headScript()
                     ->prependFile($this->basePath() . '/js/jquery.form.js?version='.$t)
				    ->prependFile($this->basePath() . '/js/admin/adminlogin.js?version='.$t);
            break;
		    }
    break;

    case 'userregistration':
        switch($action) {
            case 'userdetails':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/admin/jquery.js')
                ->prependFile($this->basePath() . '/js/admin/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/admin/csvupload.js')
                ->prependFile($this->basePath() . '/js/admin/useredit.js')
				->prependFile($this->basePath() . '/js/admin/search-user.js')
				->prependFile($this->basePath() . '/js/admin/sorttable.js');               
            break;

            case 'useredit':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/admin/useredit.js')
                ->prependFile($this->basePath() . '/js/admin/settings.js');
            break;

            case 'adduser':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/admin/useredit.js'); 
            break;

            case 'userbackupdet':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/admin/useredit.js')
                ->prependFile($this->basePath() . '/js/admin/sorttable.js');
            break;
        }
    break;

    case 'template':
		switch ($action) {
            case 'templateview':
				 $this->headScript()
                    ->prependFile($this->basePath() . '/js/admin/migrate-template.js')
                    ->prependFile($this->basePath() . '/js/admin/template-edit.js')
				    ->prependFile($this->basePath() . '/js/admin/sorttable.js');
            break;

            case 'templateedit':
				 $this->headScript()
                    ->prependFile($this->basePath() . '/js/admin/template-edit.js');
            break;
		    }
    break;

    case 'tag':
		switch ($action) {
            case 'viewtag':
				 $this->headScript()
                    ->prependFile($this->basePath() . '/js/admin/migrate-template.js')
				    ->prependFile($this->basePath() . '/js/admin/sorttable.js');
            break;

            case 'edittag':
				 $this->headScript()
                    ->prependFile($this->basePath() . '/js/admin/migrate-template.js');
            break;

            case 'addtag':
				 $this->headScript()
                    ->prependFile($this->basePath() . '/js/admin/migrate-template.js');
            break;
		    }
    break;
	
	default:
		break;
}
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery.form.js?version='.$t)    
    ->prependFile($this->basePath() . '/js/admin/logout.popup.js?version='.$t)
    ->prependFile($this->basePath() . '/js/admin/common-scripts.js?version='.$t)
    ->prependFile($this->basePath() . '/js/admin/jquery.nicescroll.js')
    ->prependFile($this->basePath() . '/js/admin/jquery.dcjqaccordion.2.7.js')
    ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
    ->prependFile('//code.jquery.com/ui/1.9.2/jquery-ui.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
?>
