<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i>Smartfanpage Tag Details
		</h3>
		<div class="col-sm-12"
             style="margin-bottom: 20px; padding: 0 !important">
             <a href="/tag/addtag" class="new_tag" title="Add tag">New Tag</a>
        </div>

		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">
				       <div class="col-md-12" style="padding: 0px 10px;">
                       </div>
                        <table class="table table-striped table-advance table-hover tbody userDetails datatable sortable" name="userDetails" id="userDetails">

						<thead>
							<tr class="show_rows">
								<th style="cursor: pointer; font-weight: bold;" class="hidden-phone email-width"><i
									class="fa fa-bookmark"></i> Name</th>
								<th style="cursor: pointer; font-weight: bold;" class="hidden-phone email-width"><i
									class="fa fa-bookmark"></i> Description</th>
								<th style="cursor: pointer; font-weight: bold;" class="hidden-phone email-width"><i
									class="fa fa-bookmark"></i> Replace Code</th>
								<th class="hidden-phone" style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Creation Date</th>
								<th style="cursor: pointer; font-weight: bold;" class="sorttable_nosort"><i
									class="fa fa-bookmark"></i> Action</th>
							</tr>
						</thead>

						<tbody class="my_size">
							<?php if(!empty($tagdata)){
								foreach($tagdata as $key => $val)
					               { ?>
							<tr	class="manageAll catId show_rows">
								<td class="hidden-phone email-width"><?php if(!empty($val['tagName'])){
                                    echo htmlspecialchars($val['tagName']); } else{ echo "N/A"; }
                                    ?></td>
								<td class="hidden-phone email-width"><span class=""
									style=""><?php echo substr(htmlspecialchars($val['tagDescription']),0,50); ?>
								</span></td>
								<td class="hidden-phone email-width"><span class=""
									style="width: 80%; display: inline-block;"><?php echo substr(htmlspecialchars($val['replaceCode']),0,50);?>
								</span></td>
								<td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['timeStamp'];?>
								</span></td>
								<input type="hidden"  class="hidden_class" value="<?php echo $val['SFPtagId']; ?>" />
								<td class="sorttable_nosort">
                                    <a href="<?php echo '/tag/edittag/'.$val['SFPtagId']; ?>" title="Edit tag details">
                                            <button class="btn btn-primary btn-xs editTag">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                    </a>
									        <button class="btn btn-danger btn-xs dlt_nom deleteTag" title="Delete tag">
										        <i class="fa fa-trash-o"></i>
									        </button>
								</td>
							</tr>
							<?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->
			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup -->
	<section id="dynamicpagecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	<div id="" class="chang_PPopup">
    <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/tag/deltag" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicpagecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete Tag</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" id="hidden_userid" class="hidden_id" />
				<h4 class="form-login-heading">Are you sure you want to delete this tag?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicpagecreatepopup').hide();" id="btn" value="CANCEL"/>
					<input class="popup_ok" type="submit" value="OK"/>
				</div>
			</div>
		</form>
	</div>
    <!--tab-content-->
    </div>
    </section>
    <!-- /delete popup-->
</section>
<!-- /MAIN CONTENT -->
