<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
	case 'p':
		switch ($action) {
			case 'useraccountdetails':
                 $this->headLink()
                      ->prependStylesheet($this->basePath() . '/css/editor/popup-alert.css?version='.$t)
                     ->prependStylesheet($this->basePath() . '/css/user/style.css?version='.$t)
                     ->prependStylesheet($this->basePath() . '/css/front/style.css?version=' . $t)
                     ->prependStylesheet($this->basePath() . '/css/common/upperlayout.css?version='.$t);
                break;
                }
            default:

            break;
    }
    echo $this->headLink()

    ->prependStylesheet($this->basePath() . '/css/common/generalpopup.css?version='.$t)
    ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css?version='.$t)
    ->prependStylesheet($this->basePath() . '/css/front/normalise.css?version='.$t)
    ->prependStylesheet($this->basePath() . 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css')
    ->prependStylesheet($this->basePath() . 'https://fonts.googleapis.com/css?family=Ubuntu:400,500,700')
    ->prependStylesheet($this->basePath() . 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,600,300' )
    ->prependStylesheet($this->basePath() . 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,600,300' );

?>
