<?php

$controller = strtolower($controller);
$action = strtolower($action);
$t = time();

switch ($controller) {
    case 'p':
        switch ($action) {

            case 'useraccountdetails':
                $this->headScript()
                ->prependFile($this->basePath() . '/js/dashboard/logout.js?version=' . $t)
                ->prependFile($this->basePath() . '/js/profile/gotopayment.js?version=' . $t)    
                ->prependFile($this->basePath() . '/js/user/changedetails.js?version=' . $t)
                ->prependFile($this->basePath() . '/js/dashboard/logout.js?version=' . $t);

                break;

            default:
                break;
        }
        break;

    default:
        break;
}
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/editor/jquery.form.js?version='.$t)
        ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
        ->prependFile('//code.jquery.com/ui/1.9.2/jquery-ui.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
?>
