<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i>Smartfanpage User Registration
		</h3>

		<!-- BASIC FORM ELELEMNTS -->
		<div class="row mt">
			<div class="col-lg-12">

        <!-- add user layout -->
				<div class="container">
                    <form class="form-login reg-form" id='adduserForm' method="post" enctype="multipart/form-data">
                    <h2 class="form-login-heading">Registration</h2>
                        <div class="reg-wrap">
                            <input type="text" name="emailReg" id="emailReg" class="form-control" placeholder="Email" autofocus>
                            <span id="errorReg" style="color: red; text-align: center;"></span>
                            <br>
                            <input type="password" name="passReg" id="passReg" class="form-control" placeholder="Password">
                            <span id="errorPass" style="color: red; text-align: center;"></span>
                            <br>
                            <input type="button" class="btn btn-theme btn-block" id="regSave" value="Register">
                        </div>
                    </form>
                </div>
        <!-- /add user layout -->

			</div>
			<!-- /col-lg-12 -->
	</div>
		<!-- /row -->
	</section>
	<!--/wrapper -->
</section>
<!-- /MAIN CONTENT -->
