
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>travel</title>
     <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->basePath('images/favicon.ico') ?>" />
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <?php include 'css.phtml'; ?>
        <?php include_once('js.phtml'); ?>
</head>
<body>
    <?php include 'navbar.phtml'; ?>
    <!--[if lt IE 8]>
		<div style=' clear: both; text-align:center; position: relative;'>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
				<img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
			</a>
		</div>
		<![endif]-->
		<!--[if lt IE 9]>
		<script src="js/front/html5shiv.js"></script>
		<link rel="stylesheet" media="screen" href="css/front/ie.css">
		<![endif]-->
    <?php echo $this->content; ?>
    <?php include 'footer.phtml'; ?>
</body>
</html>
