<header>
    <div class="container_12">
				<div class="grid_12">
					<div class="menu_block">
						<nav class="horizontal-nav full-width horizontalNav-notprocessed">
							<ul class="sf-menu">
								<li class="current"><a href="<?php echo $dynamicPath;?>">ABOUT</a></li>
								<li><a href="<?php echo $dynamicPath;?>/Gallery/tour">HOT TOURS</a></li>
								<li><a href="<?php echo $dynamicPath;?>/Gallery/offer">SPECIAL OFFERS</a></li>
								<li><a href="<?php echo $dynamicPath;?>/Gallery/blog">BLOG</a></li>
								<li><a href="<?php echo $dynamicPath;?>/Gallery/contact">CONTACTS</a></li>
							</ul>
						</nav>, 
						<div class="clear"></div>
					</div>
				</div>
				<div class="grid_12">
					<h1>
						<a href="<?php echo $dynamicPath;?>">
							<img src="images/logo.png" alt="Your Happy Family">
						</a>
					</h1>
				</div>
			</div>
</header>